FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update && apt-get install -y git libpq-dev gcc && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY rssa-storage /rssa-storage

COPY rssa-api .

RUN uv pip install --system -e /rssa-storage
RUN uv pip install --system -e .
